#!/usr/bin/env bash

# This script relies on fswatch (you can get that using homebrew)
#
# It watches the local working directory for changes, and invokes
# scripts/install-dev on each change to enable rapid development.
#
# So you don't need to look, it verbally announces the last line
# of the invoked script; turn your sound on ;)

s() { say -v Amelie "$@" & }
fin() { s "Bye!"; echo; exit 0; }
say -v Amelie "Bon jour!" 
build() {
	afplay -v 0.5 /System/Library/Sounds/Glass.aiff &
	if result=$(./scripts/install-dev); then
		s "Sous OK!"
	else
		s "Non!"
	fi
	#s $(echo "$result" | tail -n1)
	echo "$result"
}
trap fin SIGINT SIGTERM
echo "Building current version..."
build
echo
while true; do
	echo "Waiting for changes..."
	fswatch -1ri '\.go$' -e '.*' . | while read x; do echo "Changed: ${x#$PWD/}"; done
	build
	echo
done

